version: '3.8'

services:
  rankmatrix-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/rankmatrix
      - /rankmatrix/node_modules
    command: pnpm run dev
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: always
